"""changed m2m

Revision ID: 53f276914462
Revises: 1315d3f72209
Create Date: 2024-12-03 15:13:00.469473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f276914462'
down_revision = '1315d3f72209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
